// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.3.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#ifdef __cpp_constexpr
#define __pio_const constexpr
#else
#define __pio_const const
#endif

// ------ //
// rdm_rx //
// ------ //

#define rdm_rx_wrap_target 0
#define rdm_rx_wrap 10
#define rdm_rx_pio_version 0

static __pio_const uint16_t rdm_rx_program_instructions[] = {
            //     .wrap_target
    0x2020, //  0: wait   0 pin, 0
    0xe027, //  1: set    x, 7
    0x0042, //  2: jmp    x--, 2
    0xa0d3, //  3: mov    isr, ::null
    0xe047, //  4: set    y, 7
    0x4001, //  5: in     pins, 1
    0xe02d, //  6: set    x, 13
    0x0047, //  7: jmp    x--, 7
    0x0085, //  8: jmp    y--, 5
    0x8020, //  9: push   block
    0x0000, // 10: jmp    0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program rdm_rx_program = {
    .instructions = rdm_rx_program_instructions,
    .length = 11,
    .origin = -1,
    .pio_version = rdm_rx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config rdm_rx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + rdm_rx_wrap_target, offset + rdm_rx_wrap);
    return c;
}
#endif

