[env:pico]
platform = raspberrypi
board = rpipico
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 0
lib_ldf_mode = chain+
lib_deps =
    lostcaggy/CaggyRotary@^1.0.0
    adafruit/Adafruit MCP23017 Arduino Library@^2.3.2
monitor_speed = 115200
