// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.3.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#ifdef __cpp_constexpr
#define __pio_const constexpr
#else
#define __pio_const const
#endif

// ------ //
// dmx_tx //
// ------ //

#define dmx_tx_wrap_target 4
#define dmx_tx_wrap 7
#define dmx_tx_pio_version 0

static __pio_const uint16_t dmx_tx_program_instructions[] = {
    0xf037, //  0: set    x, 23           side 0
    0x0741, //  1: jmp    x--, 1                 [7]
    0xbf42, //  2: nop                    side 1 [7]
    0xbf42, //  3: nop                    side 1 [7]
            //     .wrap_target
    0x9fa0, //  4: pull   block           side 1 [7]
    0xf327, //  5: set    x, 7            side 0 [3]
    0x6001, //  6: out    pins, 1
    0x0246, //  7: jmp    x--, 6                 [2]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program dmx_tx_program = {
    .instructions = dmx_tx_program_instructions,
    .length = 8,
    .origin = -1,
    .pio_version = dmx_tx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config dmx_tx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + dmx_tx_wrap_target, offset + dmx_tx_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

